# Generated by Django 3.0.4 on 2021-05-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='first name of the user', max_length=40, unique=True)),
                ('middle_name', models.CharField(blank=True, help_text='middle name of the user', max_length=40)),
                ('last_name', models.CharField(help_text='last name of the user', max_length=40)),
                ('email', models.CharField(help_text='email of the user', max_length=40)),
                ('phone_number', models.IntegerField(max_length=20)),
                ('created_by', models.IntegerField()),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_date_time', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField()),
            ],
        ),
    ]
