# Generated by Django 3.0.4 on 2021-05-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='users',
            name='modified_by',
        ),
    ]
